"""Resolve every ticker the hub can browse into `dashboard_hub/companies.json`.

The Companies desk opens with a grid, and a grid of bare tickers is a worse
index than a grid of names — but resolving ~300 names costs one Yahoo call each,
which is far too slow to do on page load. So it is done once, here, and the
result is committed beside `sectors.json`.

The universe is the union of two lists that overlap but neither contains the
other: every constituent of every editorial sector, plus every issuer the
warehouse actually carries filings for. Names in both are flagged `warehouse`,
which is what lets the detail page offer an as-filed panel.

    make company-universe

Re-run it after editing `sectors.json` or `companies.yml`. Nothing else reads
Yahoo at build time; live prices and financials are still fetched per request.
"""

from __future__ import annotations

import json
import math
import sys
import time
from pathlib import Path
from typing import Any

import yaml
import yfinance as yf

REPO_ROOT = Path(__file__).resolve().parent.parent
SECTORS_PATH = REPO_ROOT / "dashboard_hub" / "sectors.json"
COMPANIES_YML = REPO_ROOT / "ingestion" / "config" / "companies.yml"
OUT_PATH = REPO_ROOT / "dashboard_hub" / "companies.json"

# Yahoo throttles a tight loop of profile requests. A short pause between calls
# and a couple of retries is the difference between a full file and a third of one.
PAUSE_SECONDS = 0.15
RETRIES = 2
RETRY_BACKOFF = 2.0

NOTE = (
    "Generated by scripts/generate_company_universe.py — do not hand-edit. "
    "The universe is every constituent of sectors.json plus every issuer in "
    "companies.yml. Names, sectors and countries are Yahoo's own classification, "
    "resolved once at build time so the grid does not pay for them on load; "
    "prices and financials are still fetched live per request."
)


def _universe() -> tuple[dict[str, list[str]], dict[str, dict[str, Any]]]:
    """Every symbol the hub can browse, with what each source knows about it.

    Returns:
        `(sector_slugs_by_symbol, warehouse_rows_by_ticker)`. A symbol in the
        second but not the first is a holding no editorial sector claims.
    """
    with SECTORS_PATH.open(encoding="utf-8") as handle:
        sectors = json.load(handle)["sectors"]

    membership: dict[str, list[str]] = {}
    for sector in sectors:
        for symbol in sector["symbols"]:
            membership.setdefault(symbol, []).append(sector["slug"])

    with COMPANIES_YML.open(encoding="utf-8") as handle:
        holdings = yaml.safe_load(handle)["companies"]
    warehouse = {row["ticker"]: row for row in holdings}

    for ticker in warehouse:
        membership.setdefault(ticker, [])
    return membership, warehouse


def _profile(symbol: str) -> dict[str, Any]:
    """Yahoo's classification of one listing, or empty if it will not answer."""
    for attempt in range(RETRIES + 1):
        try:
            info = yf.Ticker(symbol).info or {}
            if info.get("shortName") or info.get("longName"):
                return info
        except Exception as exc:  # noqa: BLE001 — one bad symbol must not end the run
            if attempt == RETRIES:
                print(f"  ! {symbol}: {exc}", file=sys.stderr)
        if attempt < RETRIES:
            time.sleep(RETRY_BACKOFF * (attempt + 1))
    return {}


def _domain(info: dict[str, Any]) -> str:
    """The bare domain from a company's website, for looking its mark up.

    Yahoo gives a full URL and the logo services want a hostname, so the scheme,
    any `www.` and any path are stripped. A company with no website simply has no
    logo and the grid draws a lettermark instead.
    """
    website = (info.get("website") or "").strip()
    if not website:
        return ""
    host = website.split("//")[-1].split("/")[0].strip().lower()
    if host.startswith("www."):
        host = host[4:]
    # Guard against Yahoo returning something that is not a hostname at all.
    return host if "." in host and " " not in host else ""


def _number(value: Any) -> float | None:
    """A finite float, or None — Yahoo returns strings and NaNs for absent fields."""
    if value is None:
        return None
    try:
        out = float(value)
    except (TypeError, ValueError):
        return None
    return out if math.isfinite(out) else None


def _fundamentals(info: dict[str, Any]) -> dict[str, float | None]:
    """The four figures the grid sorts on, plus the size that contextualises them.

    Trailing twelve months, as Yahoo reports it. Growth arrives as a fraction —
    0.12 for twelve percent — and is left that way; the UI formats it.
    """
    return {
        # The currency the *statements* are in, which for an ADR is not the one
        # the shares trade in: Toyota's TM trades in USD and files in JPY. Using
        # the trading currency here ranked Toyota's revenue at $50,685bn.
        "financialCurrency": info.get("financialCurrency") or info.get("currency") or "",
        "revenue": _number(info.get("totalRevenue")),
        "netIncome": _number(info.get("netIncomeToCommon")),
        "revenueGrowth": _number(info.get("revenueGrowth")),
        "earningsGrowth": _number(info.get("earningsGrowth"))
        or _number(info.get("earningsQuarterlyGrowth")),
        "marketCap": _number(info.get("marketCap")),
        "profitMargin": _number(info.get("profitMargins")),
    }


def _rates(currencies: set[str]) -> dict[str, float]:
    """Units of each currency per USD, in one batch.

    Sorting a grid by "highest revenue" is meaningless until the figures share a
    unit: Toyota reports ¥50,685bn and Apple $467bn, and a naive sort puts Toyota
    six places too high purely because the yen is small. Growth rates need none
    of this — a percentage is currency-neutral — but levels do.
    """
    wanted = {c for c in currencies if c and c.upper() not in ("USD",)}
    rates: dict[str, float] = {"USD": 1.0}
    if not wanted:
        return rates

    # Some London listings report in pence rather than pounds.
    symbols = sorted({f"{'GBP' if c.upper() == 'GBP' else c.upper()}=X" for c in wanted})
    try:
        frame = yf.download(
            symbols, period="5d", interval="1d", progress=False, auto_adjust=True, threads=True
        )["Close"]
    except Exception as exc:  # noqa: BLE001 — no FX means levels stay unconverted
        print(f"  ! FX lookup failed ({exc}); levels will not be normalised", file=sys.stderr)
        return rates

    for currency in wanted:
        code = currency.upper()
        column = f"{code}=X"
        if column not in frame:
            continue
        series = frame[column].dropna()
        if series.empty:
            continue
        rates[currency] = float(series.iloc[-1])

    # GBp is pence: a hundred of them to the pound.
    if "GBp" in wanted and "GBP" in rates:
        rates["GBp"] = rates["GBP"] * 100
    return rates


def main() -> int:
    membership, warehouse = _universe()
    symbols = sorted(membership)
    print(f"Resolving {len(symbols)} symbols — {len(warehouse)} of them warehouse holdings.")

    companies: list[dict[str, Any]] = []
    unresolved: list[str] = []
    for index, symbol in enumerate(symbols, start=1):
        info = _profile(symbol)
        held = warehouse.get(symbol)
        # The warehouse's own legal name wins where it has one: it comes from the
        # filing, and this grid sits next to figures drawn from that same filing.
        name = (
            (held or {}).get("legal_name")
            or info.get("longName")
            or info.get("shortName")
            or symbol
        )
        if not info:
            unresolved.append(symbol)

        companies.append(
            {
                "symbol": symbol,
                "name": name,
                "sector": info.get("sector") or (held or {}).get("sector") or "",
                "industry": info.get("industry") or "",
                "country": info.get("country") or (held or {}).get("country") or "",
                "currency": info.get("currency") or "",
                "exchange": info.get("fullExchangeName") or info.get("exchange") or "",
                "domain": _domain(info),
                "sectors": membership[symbol],
                "warehouse": symbol in warehouse,
                **_fundamentals(info),
            }
        )
        if index % 25 == 0 or index == len(symbols):
            print(f"  {index}/{len(symbols)}")
        time.sleep(PAUSE_SECONDS)

    # Levels are converted to USD so the grid can rank them against each other;
    # the reported figure and its currency are both kept beside the conversion.
    rates = _rates({entry["financialCurrency"] for entry in companies})
    converted, unconverted = 0, []
    for entry in companies:
        reported = entry["financialCurrency"] or entry["currency"]
        rate = rates.get(reported)
        for field in ("revenue", "netIncome", "marketCap"):
            value = entry.get(field)
            entry[f"{field}Usd"] = value / rate if value is not None and rate else None
        if reported and reported != "USD":
            if rate:
                converted += 1
            else:
                unconverted.append(f"{entry['symbol']} ({reported})")

    if unconverted:
        print(f"  ! no rate for {', '.join(unconverted)} — their levels stay unranked")

    print(f"Normalised {converted} non-USD listings using {len(rates)} rates.")
    payload = {"note": NOTE, "companies": companies}
    with OUT_PATH.open("w", encoding="utf-8") as handle:
        json.dump(payload, handle, indent=2, ensure_ascii=False)
        handle.write("\n")

    print(f"\nWrote {len(companies)} companies to {OUT_PATH.relative_to(REPO_ROOT)}")
    if unresolved:
        print(f"Unresolved (kept with the symbol as the name): {', '.join(unresolved)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
