"""Resolve every ticker the hub can browse into `dashboard_hub/companies.json`.

The Companies desk opens with a grid, and a grid of bare tickers is a worse
index than a grid of names — but resolving ~300 names costs one Yahoo call each,
which is far too slow to do on page load. So it is done once, here, and the
result is committed beside `sectors.json`.

The universe is the union of two lists that overlap but neither contains the
other: every constituent of every editorial sector, plus the 38 holdings the
warehouse actually carries filings for. Names in both are flagged `warehouse`,
which is what lets the detail page offer an as-filed panel.

    make company-universe

Re-run it after editing `sectors.json` or `companies.yml`. Nothing else reads
Yahoo at build time; live prices and financials are still fetched per request.
"""

from __future__ import annotations

import json
import sys
import time
from pathlib import Path
from typing import Any

import yaml
import yfinance as yf

REPO_ROOT = Path(__file__).resolve().parent.parent
SECTORS_PATH = REPO_ROOT / "dashboard_hub" / "sectors.json"
COMPANIES_YML = REPO_ROOT / "ingestion" / "config" / "companies.yml"
OUT_PATH = REPO_ROOT / "dashboard_hub" / "companies.json"

# Yahoo throttles a tight loop of profile requests. A short pause between calls
# and a couple of retries is the difference between a full file and a third of one.
PAUSE_SECONDS = 0.15
RETRIES = 2
RETRY_BACKOFF = 2.0

NOTE = (
    "Generated by scripts/generate_company_universe.py — do not hand-edit. "
    "The universe is every constituent of sectors.json plus the 38 holdings in "
    "companies.yml. Names, sectors and countries are Yahoo's own classification, "
    "resolved once at build time so the grid does not pay for them on load; "
    "prices and financials are still fetched live per request."
)


def _universe() -> tuple[dict[str, list[str]], dict[str, dict[str, Any]]]:
    """Every symbol the hub can browse, with what each source knows about it.

    Returns:
        `(sector_slugs_by_symbol, warehouse_rows_by_ticker)`. A symbol in the
        second but not the first is a holding no editorial sector claims.
    """
    with SECTORS_PATH.open(encoding="utf-8") as handle:
        sectors = json.load(handle)["sectors"]

    membership: dict[str, list[str]] = {}
    for sector in sectors:
        for symbol in sector["symbols"]:
            membership.setdefault(symbol, []).append(sector["slug"])

    with COMPANIES_YML.open(encoding="utf-8") as handle:
        holdings = yaml.safe_load(handle)["companies"]
    warehouse = {row["ticker"]: row for row in holdings}

    for ticker in warehouse:
        membership.setdefault(ticker, [])
    return membership, warehouse


def _profile(symbol: str) -> dict[str, Any]:
    """Yahoo's classification of one listing, or empty if it will not answer."""
    for attempt in range(RETRIES + 1):
        try:
            info = yf.Ticker(symbol).info or {}
            if info.get("shortName") or info.get("longName"):
                return info
        except Exception as exc:  # noqa: BLE001 — one bad symbol must not end the run
            if attempt == RETRIES:
                print(f"  ! {symbol}: {exc}", file=sys.stderr)
        if attempt < RETRIES:
            time.sleep(RETRY_BACKOFF * (attempt + 1))
    return {}


def main() -> int:
    membership, warehouse = _universe()
    symbols = sorted(membership)
    print(f"Resolving {len(symbols)} symbols — {len(warehouse)} of them warehouse holdings.")

    companies: list[dict[str, Any]] = []
    unresolved: list[str] = []
    for index, symbol in enumerate(symbols, start=1):
        info = _profile(symbol)
        held = warehouse.get(symbol)
        # The warehouse's own legal name wins where it has one: it comes from the
        # filing, and this grid sits next to figures drawn from that same filing.
        name = (
            (held or {}).get("legal_name")
            or info.get("longName")
            or info.get("shortName")
            or symbol
        )
        if not info:
            unresolved.append(symbol)

        companies.append(
            {
                "symbol": symbol,
                "name": name,
                "sector": info.get("sector") or (held or {}).get("sector") or "",
                "industry": info.get("industry") or "",
                "country": info.get("country") or (held or {}).get("country") or "",
                "currency": info.get("currency") or "",
                "exchange": info.get("fullExchangeName") or info.get("exchange") or "",
                "sectors": membership[symbol],
                "warehouse": symbol in warehouse,
            }
        )
        if index % 25 == 0 or index == len(symbols):
            print(f"  {index}/{len(symbols)}")
        time.sleep(PAUSE_SECONDS)

    payload = {"note": NOTE, "companies": companies}
    with OUT_PATH.open("w", encoding="utf-8") as handle:
        json.dump(payload, handle, indent=2, ensure_ascii=False)
        handle.write("\n")

    print(f"\nWrote {len(companies)} companies to {OUT_PATH.relative_to(REPO_ROOT)}")
    if unresolved:
        print(f"Unresolved (kept with the symbol as the name): {', '.join(unresolved)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
